name: 'Round ID Linker'
description: 'Links Round IDs found in issue body'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  format-version:
    description: 'byond client version number will be formatted as downloadable links'
    required: false
    default: true
runs:
  using: 'node24'
  main: 'dist/index.js'
